
version: 2

sources:
  - name: eth
    quoting:
        database: true
        schema: true
    database: eth  
    schema: eth_schema

    tables:
      - name: contracts
        identifier: cnt
      - name: token_transfers
      - name: transactions
